version: '3'

# 永続化
volumes:
  node_modules_data:
  vendor_data:

services:
  web-nginx:
    container_name: "web-nginx"
    build:
      context: ./docker/nginx
    depends_on:
      - app-php
    ports:
      - 80:80
    volumes:
      - ./:/src

  app-php:
    container_name: "app-php"
    build:
      context: ./docker/php
    depends_on:
      - db-mysql
    ports:
      - 5173:5173
    volumes:
      - type: bind
        source: ./
        target: /src
    #*# node_modulesとvendorはbindマウントから外す #*#
      - type: volume
        source: node_modules_data
        target: /src/node_modules
      - type: volume
        source: vendor_data
        target: /src/vendor
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  db-mysql:
    image: mysql:8.0.28
    command: --max_allowed_packet=32505856
    platform: linux/amd64
    container_name: "db-mysql"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=assign_manager
    ports:
      - 3306:3306

  redis:
    image: redis:alpine
    container_name: "redis"
    ports:
      - 16379:6379
